- mautrix_instagram/portal.py
* Send UNSUPPORTED for non-image attachments.
* Send UNSUPPORTED if handling the given the event type is not implemented
* Also cleans up some of the code around sending error PERM_FAILURE checkpoints.
> checkpoints: send UNSUPPORTED for errors that won't ever be fixed

- mautrix_instagram/web/provisioning_api.py
Really hard to repro when exactly this happens, but it seems to error on the reset.
> login: send 403 if user needs to verify on their phone

- mautrix_instagram/config.py
- mautrix_instagram/example-config.yaml
- mautrix_instagram/portal.py
Added feature for m.notice-type messages not be bridged
> Added feature for m.notice-type messages not be bridged

- mauigpapi/types/thread_item.py
- mautrix_instagram/portal.py
generic_xma are the 'Mentioned you in their comment' messages. This adds
support for them.
> comment mentions: add support for generic_xma

- Dockerfile
- mauigpapi/__init__.py
- mauigpapi/http/base.py
- mauigpapi/mqtt/__init__.py
- mauigpapi/mqtt/conn.py
- mauigpapi/mqtt/events.py
- mauigpapi/proxy.py
- mautrix_instagram/commands/auth.py
- mautrix_instagram/config.py
- mautrix_instagram/example-config.yaml
- mautrix_instagram/user.py
- optional-requirements.txt
Added feature to set up a proxy
> Set up a proxy

- mauigpapi/types/__init__.py
- mauigpapi/types/thread.py
- mautrix_instagram/db/portal.py
- mautrix_instagram/db/upgrade/v12_portal_thread_image_id.py
- mautrix_instagram/portal.py
> portal: support group chat avatars

- mautrix_instagram/portal.py
> backfill: dedup when pulling more pages

- mauigpapi/types/thread_item.py
- mautrix_instagram/portal.py
> xma_profile shares: support new xma method of sharing profiles

- mautrix_instagram/portal.py
Use ffprobe to check to see if a video is not in the yuv420p format, and if it is transcode it. And add yuv420p and faststart to the encoder flags to improve the chances of Instagram accepting the video.
Requires mautrix-python release before merging!
Fixes #47 
Closes #61
> Attempt to fix Instagram returning 500 with certain videos

- mautrix_instagram/web/provisioning_api.py
Mostly copied the exception handler from a similar handler for rate limit during 2FA SMS resending
> Explicitly handle IGRateLimitError during FB login

- mauigpapi/__init__.py
- mauigpapi/mqtt/conn.py
- mauigpapi/proxy.py
- mautrix_instagram/user.py
Couple of tweaks:
+ Only get a new proxy on the 2nd attempt onwards
+ De-dupe some of the proxy exception lists
> Proxy handling improvements

- mauigpapi/proxy.py
- mautrix_instagram/web/provisioning_api.py
Possible future work here to re-use the `proxy_with_retry` helper elsewhere.
> Retry login proxy errors

- mauigpapi/types/thread_item.py
- mautrix_instagram/portal.py
> video call: handle by showing a notice

- mauigpapi/mqtt/conn.py
Missing while true meant we exited immediately rather than constantly polling the MQTT loop.
> Fix MQTT connection loop

- mauigpapi/http/base.py
- mautrix_instagram/commands/auth.py
- mautrix_instagram/portal.py
- mautrix_instagram/puppet.py
- mautrix_instagram/user.py
- mautrix_instagram/web/provisioning_api.py
Rework of https://github.com/mautrix/instagram/pull/103 that moves the retry logic into the base `AndroidAPI` class meaning everything will be wrapped.
> Proxy retry all the things redux

- mautrix_instagram/portal.py
> portal: send bridge error on ThreadUserIdDoesNotExist

- mautrix_instagram/portal.py
> captions: don't put caption text in blockquote

- mauigpapi/http/base.py
- mautrix_instagram/commands/auth.py
- mautrix_instagram/user.py
> error handling: send BAD_CREDENTIALS when a login required/logged out error occurs

- mautrix_instagram/config.py
- mautrix_instagram/example-config.yaml
- mautrix_instagram/portal.py
> typing: add option to disable Matrix -> IG

- mautrix_instagram/portal.py
> media: don't bridge caption for reels

- mautrix_instagram/portal.py
> reels: add custom field for story share/reply/reaction/mention

- mautrix_instagram/portal.py
Same issue as https://github.com/mautrix/facebook/issues/274
> Send backfill dummy events with main intent

- mautrix_instagram/portal.py
> Add missing fields from story and post shares
